# Generated by Django 4.1 on 2022-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
